spring.application.name=Inventory_web_app



#spring.datasource.username=shristi
#spring.datasource.password=shristi


spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_db
spring.datasource.username=dipendra
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true